### ISSUE TITLE
Implement .timeout

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/bluebird-api#28]

**Comment by benjamingr** [comment]
mine

**Comment by Shrulik** [comment]
I think i will take this one as well as delay, since they are similar. I think I will look into supporting cancellations as well, since it looks interesting.

**Comment by benjamingr** [comment]
@Shrulik wait with cancellation, it's hard to get done and it's a non-goal of the repo initially.

**Comment by benjamingr** [comment]
(but by all means do `.timeout`)

**Comment by Shrulik** [comment]
So I did this. The only issue is around this weirdish before : "https://github.com/petkaantonov/bluebird/blob/master/test/mocha/timers.js#L102"

It fails because globalObject.oldSetTimeout isn't defined.
I can port this whole browser timers shim thingy bluebird has going on, but do we want it ? 
From skimming the history, it seems this is for old IE testing support, which we really don't care about, so I'm for killing it.

**Comment by benjamingr** [comment]
That's fine.

**Comment by Shrulik** [comment]
So a bit of a quandry. According to bluebird tests, timeout on a child promise, should reject the parent promise as well ( bluebird has a test named "should cancel the parent promise once the timeout expires" ).

As far as I can see, native promises don't behave this way. What approach should we take ? 
plunker for native version :
https://plnkr.co/edit/uLF66O2KdXTxJmGSG8ND?p=preview

Maybe I'm missing something.

**Comment by benjamingr** [comment]
@Shrulik we're not doing cancellation. 

So you should just support the behavior without cancellation. timeout does not impact parent.
