### ISSUE TITLE
Implement promisifyAll

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/bluebird-api#6]

**Comment by luggage66** [comment]
On it.

**Comment by luggage66** [comment]
Status: Almost done. In-progress code in a branch. 55/ 65 tests passing. I might be able to merge later tonight. Maybe tomorrow.

**Comment by luggage66** [comment]
Merged

- 1 test commented out (depends on promise.isPending() which I think is a non-goal)
- 3 tests .skip'ed, waiting for #52 
- 1 test .skip'ed because I think it might not apply.. not sure. It tests arity and I think that is only valid for bluebird's "eval" code path
- 1 test .skip'ed, waiting for custom schedulers

The other 62 pass.

**Comment by benjamingr** [comment]
Sweet.
